// TheCoffeeCream/mobile/apps/app-staff/src/features/auth/pages/Login.jsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '@thecoffeecream/ui-shared'
import logo from '@/assets/icons/logo.png'
import './Login.scss'

/**
 * Login screen for staff members
 */
export default function Login() {
    const { login } = useAuth()
    const navigate = useNavigate()
    const [credentials, setCredentials] = useState({ username: '', password: '' })
    const [error, setError] = useState('')
    const [loading, setLoading] = useState(false)

    const handleChange = (e) => {
        const { name, value } = e.target
        setCredentials(prev => ({ ...prev, [name]: value }))
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        setError('')
        setLoading(true)

        try {
            await login(credentials.username, credentials.password)
            navigate('/')
        } catch (err) {
            setError(err.message || 'Sai tài khoản hoặc mật khẩu.')
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="login-page" data-theme="dark">
            <div className="login-container">
                <div className="login-card">
                    <div className="login-header">
                        <div className="brand-logo-wrapper">
                            <img src={logo} alt="The Coffee Cream" className="brand-logo" />
                        </div>
                        <div className="brand-name">THE COFFEE CREAM</div>
                        <p>Hệ thống quản lý nội bộ</p>
                    </div>

                    <form onSubmit={handleSubmit} className="login-form">
                        <div className="form-group">
                            <label htmlFor="username">Tên đăng nhập</label>
                            <input
                                id="username"
                                type="text"
                                name="username"
                                value={credentials.username}
                                onChange={handleChange}
                                placeholder="Nhập username..."
                                required
                                autoComplete="username"
                            />
                        </div>

                        <div className="form-group">
                            <label htmlFor="password">Mật khẩu</label>
                            <input
                                id="password"
                                type="password"
                                name="password"
                                value={credentials.password}
                                onChange={handleChange}
                                placeholder="Nhập password..."
                                required
                                autoComplete="current-password"
                            />
                        </div>

                        {error && <div className="error-alert">{error}</div>}

                        <button
                            type="submit"
                            className={`login-btn ${loading ? 'loading' : ''}`}
                            disabled={loading}
                        >
                            {loading ? (
                                <span className="spinner"></span>
                            ) : (
                                'ĐĂNG NHẬP'
                            )}
                        </button>
                    </form>

                    <footer className="login-footer">
                        <p>Phát triển bởi <strong>The Coffee Cream Team</strong></p>
                        <p className="version">Phiên bản 2.0.0 (Staff App)</p>
                    </footer>
                </div>
            </div>

            <div className="bg-shapes">
                <div className="shape shape-1"></div>
                <div className="shape shape-2"></div>
                <div className="shape shape-3"></div>
            </div>
        </div>
    )
}

// TheCoffeeCream/mobile/apps/app-owner/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  standalone: false
})
export class LoginComponent {
  username = '';
  password = '';
  loading = false;
  error = '';

  constructor(private auth: AuthService, private router: Router) {
    if (this.auth.isLoggedIn() && this.auth.isSuperAdmin()) {
      this.router.navigate(['/shops']);
    }
  }

  onSubmit(): void {
    if (!this.username || !this.password) return;

    this.loading = true;
    this.error = '';

    this.auth.login({ username: this.username, password: this.password }).subscribe({
      next: (res) => {
        if (this.auth.isSuperAdmin()) {
          this.router.navigate(['/shops']);
        } else {
          this.error = 'Access denied. Only Super Admins can access this portal.';
          this.auth.logout();
        }
      },
      error: (err) => {
        this.error = err.error || 'Login failed. Please check your credentials.';
        this.loading = false;
      }
    });
  }
}

<div class="login-page">
  <!-- Animated Background Shapes -->
  <div class="bg-shapes">
    <div class="shape shape-1"></div>
    <div class="shape shape-2"></div>
    <div class="shape shape-3"></div>
  </div>

  <div class="login-container">
    <div class="login-card">
      <div class="login-header">
        <div class="brand-logo-wrapper">
          <img src="assets/icons/logo.png" alt="Logo" class="brand-logo">
        </div>
        <h1 class="brand-name">Owner Portal</h1>
        <p>Log in to manage your shops</p>
      </div>

      <form (ngSubmit)="onSubmit()" class="login-form">
        <div class="form-group">
          <label>Username</label>
          <input type="text" name="username" [(ngModel)]="username" placeholder="Enter username" required>
        </div>

        <div class="form-group">
          <label>Password</label>
          <input type="password" name="password" [(ngModel)]="password" placeholder="••••••" required>
        </div>

        <div *ngIf="error" class="error-alert">
          {{ error }}
        </div>

        <button type="submit" [disabled]="loading" class="login-btn" [class.loading]="loading">
          <span *ngIf="!loading">Login</span>
          <div *ngIf="loading" class="spinner"></div>
        </button>
      </form>

      <div class="login-footer">
        <p><strong>THE COFFEE CREAM</strong></p>
        <p class="version">v1.0.0 (Owner App)</p>
      </div>
    </div>
  </div>
</div>
