// TheCoffeeCream/mobile/apps/ui-shared/src/components/ui/Toast/index.jsx
import { Icon } from '../Icon'
import './Toast.css'

export function Toast({ message, visible, type = 'success', action }) {
    return (
        <div className={`app-toast ${visible ? 'visible' : ''} type-${type}`} role="status" aria-live="polite">
            <div className="toast-inner">
                <Icon name={type === 'error' ? 'alert-circle' : 'check'} size={20} className="toast-check-icon" />
                <div className="toast-msg">{message}</div>
                {action && (
                    <button
                        className="toast-action-btn"
                        onClick={action.onClick}
                    >
                        {action.label}
                    </button>
                )}
            </div>
        </div>
    )
}

// TheCoffeeCream/mobile/apps/app-owner/src/app/shared/components/toast/toast.component.ts
import { Component } from '@angular/core';
import { ToastService, ToastType } from '../../services/toast.service';
import { Observable } from 'rxjs';

@Component({
    selector: 'app-toast',
    templateUrl: './toast.component.html',
    styleUrls: ['./toast.component.scss'],
    standalone: false
})
export class ToastComponent {
    show$: Observable<boolean>;
    message$: Observable<string>;
    type$: Observable<ToastType>;
    action$: Observable<{ label: string, callback: () => void } | null>;

    constructor(private toastService: ToastService) {
        this.show$ = this.toastService.show$;
        this.message$ = this.toastService.message$;
        this.type$ = this.toastService.type$;
        this.action$ = this.toastService.action$;
    }

    handleAction(action: { label: string, callback: () => void }): void {
        if (action && action.callback) {
            action.callback();
        }
        this.toastService.hide();
    }
}

<div class="app-toast type-{{ type$ | async }}" [class.visible]="show$ | async" role="status" aria-live="polite">
    <div class="toast-inner">
        <div class="toast-check-icon">
            <!-- SVG Icon based on type -->
            <svg *ngIf="(type$ | async) === 'success'" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round">
                <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
            <svg *ngIf="(type$ | async) === 'error'" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round">
                <line x1="18" y1="6" x2="6" y2="18"></line>
                <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
            <svg *ngIf="(type$ | async) === 'warning'" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z">
                </path>
                <line x1="12" y1="9" x2="12" y2="13"></line>
                <line x1="12" y1="17" x2="12.01" y2="17"></line>
            </svg>
            <svg *ngIf="(type$ | async) === 'info'" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="16" x2="12" y2="12"></line>
                <line x1="12" y1="8" x2="12.01" y2="8"></line>
            </svg>
        </div>
        <div class="toast-msg">{{ message$ | async }}</div>

        <button *ngIf="action$ | async as action" class="toast-action-btn" (click)="handleAction(action)">
            {{ action.label }}
        </button>
    </div>
</div>
